controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_eleve_search:
    path: /eleve/search
    controller: App\Controller\EleveCrudController::search
